### ISSUE TITLE
...

### ISSUE THREAD

**Issue by Jameingx** [MatiDebugging/voiceChat.EN#2]
Since this project was a joke, did I just download a virus?

**Comment by MatiDebugging** [comment]
Yes, you are correct.

**Comment by Jameingx** [comment]
That's funny, because my browser IMMEDIATELY deleted it. I guess it still knew I downloaded a virus.

**Comment by MatiDebugging** [comment]
Good, the virus doesn't really do anything. It just restarts your pc and
deletes some random software it finds.
